# Google Cloud Build configuration for automatic deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/divvydo:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/divvydo:latest'
      - '.'
    id: 'build-image'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/divvydo:$COMMIT_SHA'
    id: 'push-image'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'divvydo'
      - '--image'
      - 'gcr.io/$PROJECT_ID/divvydo:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'VITE_SUPABASE_URL=${_SUPABASE_URL},VITE_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
    id: 'deploy-cloud-run'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/divvydo:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/divvydo:latest'

# Substitutions for environment variables
substitutions:
  _SUPABASE_URL: '' # Set in Cloud Build triggers
  _SUPABASE_ANON_KEY: '' # Set in Cloud Build triggers

# Timeout for the entire build
timeout: 1200s
